### ISSUE TITLE
Clang format error.

### ISSUE THREAD

**Issue by gbalduzz** [CompFUSE/DCA#109]
Since the update of the clang-format file, I get the following error.
```
YAML:66:24: error: unknown key 'SortUsingDeclarations'
```
Also, I am not sure if it is related, but I get line breaks after 80 characters instead of 100.

I tried clang-format 3.9 and 4. Which one are we supposed to use?

**Comment by uhaehner** [comment]
clang-format >= 6.0 should work.
We had to move on since MacOS Mojave does not support LLVM 4.0 anymore.
@gbalduzz Let me know if the line break problem remains.

**Comment by gbalduzz** [comment]
It works with clang-format 7.0 (did not try 6.0) and the additional change in #110.
I think it would have been nice to have a PR for 49b2c8a664b58e5d4fe31f928e2db59f70fdaa2b documenting the change.

**Comment by uhaehner** [comment]
It works with 6.0, too.
I'll keep this issue open as long as there's still the TODO item

**Comment by uhaehner** [comment]
The required version of ClangFormat is now documented in the wiki:
https://github.com/CompFUSE/DCA/wiki/Coding-style.
