### ISSUE TITLE
Sign is jumping in bilayer-lattice calculations

### ISSUE THREAD

**Issue by cosdis** [CompFUSE/DCA#133]
The jumping sign is caused by the commit: writing/reading walker configuration 491ab8e. The issue appears after this commit. I have put the results from the version with this commit and the version with one commit earlier in /gpfs/alpine/proj-shared/cph102/mai/jumping_sign.

f4b5be9 good
491ab8e bad

**Comment by gbalduzz** [comment]
PR #134 allows to not read the configuration (by defualt) This would provide a quick fix while we understand if there is any problem in reading a multiband configuration.
