### ISSUE TITLE
Thread affinity code does not compile on MacOS

### ISSUE THREAD

**Issue by ubulling** [CompFUSE/DCA#139]
The thread affinity code, i.e.
https://github.com/CompFUSE/DCA/blob/master/src/parallel/stdthread/thread_pool/affinity.cpp
 uses linux specific methods and structures such as `sched_getaffinity()` and `cpu_set_t`, which are not available on MacOS.
This might be a possible workaround for MacOS: https://yyshen.github.io/2015/01/18/binding_threads_to_cores_osx.html

**Comment by uhaehner** [comment]
New proposed workaround: no-op for any non-linux system.

**Comment by ubulling** [comment]
Could someone please fix this?

**Comment by ubulling** [comment]
Addressed by PR #185.
