### ISSUE TITLE
Possible bug in symmetrization 

### ISSUE THREAD

**Issue by gbalduzz** [CompFUSE/DCA#142]
from `symmetrize_single_particle_function.hpp:681`
```
          int K_new_ind = k_symmetry_matrix(k_ind, b0, S_ind).first;  // FIXME: b0 -> b1

          int b0_new = k_symmetry_matrix(0, b0, S_ind).second;
          int b1_new = k_symmetry_matrix(k_ind, b1, S_ind).second;

          f_new(b0, b1, k_ind) += f(b0_new, b1_new, K_new_ind);
```
It looks like this code allows the symmetric orbitals to sit on different bands. Not that it affects any of the currently used models, but is the second line correct, or 0 is a typo and it should be `k_ind` instead? Also does anyone know what the "FIXME" comment refers to?

**Comment by uhaehner** [comment]
I think I have stumbled upon this before and put the FIXME comment.
My understanding was that k_ind_0 is set to zero and k_ind_1 = k_ind.
That's why I assumed it should be b1 in the first line.
Does this make sense?

**Comment by gbalduzz** [comment]
I don't think I understand. I thought that k_symmetry_matrix is set so that 
f(b, k) = f(k_symmetry_matrix(k, b, s).second, k_symmetry_matrix(k, b, s).first) for any s. 
I.e.  first maps to the equivalent k' point and second maps to the equivalent band. Though we do not have any symmetry that mixes bands that would expose it, not it is very clear how it is supposed to work for a function of two bands.

Also Me, Thomas and Phezhi are currently running a model with different (anti)symmetries on different bands, so ideally the code should be updated to allow it. I think the symmetry type should be a property of the model, rather than a template argument to be set independently, maybe with an option to turn cluster symmetries off.

**Comment by gbalduzz** [comment]
After playing around with the symmetrization code more it seems correct but confusing: the symmetries of b in k space are built from the real cluster.
