### ISSUE TITLE
Parameters wiki page duplicated and out of date

### ISSUE THREAD

**Issue by uhaehner** [CompFUSE/DCA#148]
See my last comment in PR #143.

**Comment by gbalduzz** [comment]
We decided with @PDoakORNL to keep at least the most frequently changed files in the main repo, so that they share the same history as the code and the changes in the PR are consistent with the Wiki. As you can link files from anywhere in the Wiki, there should not be any problem.

**Comment by uhaehner** [comment]
The official *Wiki* is still out of date.
As the main documentation it is referenced on the main page of the repo and in the release paper and, hence, should be kept up to date with any API changes that arrive in master.

**Comment by gbalduzz** [comment]
The wiki page refers to the file in the DCA repo, which is up to date. After checking that the link works I removed the duplicated file. Does the paper reference the wiki page or the specific Parameters.md file?

**Comment by uhaehner** [comment]
Ok, the link on Home works, but the link in the content bar is now broken.
There's no reference to the specific wiki page. So, it should be fine if the content bar link is fixed, too.

**Comment by uhaehner** [comment]
@gbalduzz Also, please restore the trailing whitespaces for correct formatting.
