### ISSUE TITLE
NiO test fails too often.

### ISSUE THREAD

**Issue by gbalduzz** [CompFUSE/DCA#21]
The NIO statistical test fails more than the expected 1% of times. If it is not caused by https://github.com/CompFUSE/DCA-develop/issues/185 it might mean that there is some small issue with the SS-HYB solver.
The effects of https://github.com/CompFUSE/DCA-develop/issues/185 are easy to eliminate and test, but otherwise, this should be fixed after the merging of `gpu_trunk`, and depending on the amount of interest in the hybridization solver.

**Comment by uhaehner** [comment]
@gbalduzz I would start by changing the RNG. The test still uses ranlux48_base, which was not good enough for CT-AUX.

**Comment by gbalduzz** [comment]
Thanks, I did not realize that. I will see if that is the culprit.

**Comment by gbalduzz** [comment]
Duplicate of #11.
