### ISSUE TITLE
Macro for DCA_WITH_CUDA_AWARE_MPI

### ISSUE THREAD

**Issue by weilewei** [CompFUSE/DCA#217]
I found that several macros `DCA_WITH_CUDA_AWARE_MPI` in this file, are they supposed to be `DCA_HAVE_CUDA_AWARE_MPI`? 

https://github.com/CompFUSE/DCA/blob/master/include/dca/phys/dca_step/cluster_solver/shared_tools/accumulation/tp/tp_accumulator_mpi_gpu.hpp#L369

If I replace them, the ringG tests will fail unless adding `--smpiargs="-gpu" ./cvdlauncher.sh`

**Comment by gbalduzz** [comment]
Thanks for spotting it! I forgot the weird convention of having different names for cmake options and c++ macros.
It should work even without the cvdlauncher.
