### ISSUE TITLE
Extensive tests fail on Summit

### ISSUE THREAD

**Issue by yingwaili** [CompFUSE/DCA#67]
On Summit, all the fast tests pass but extensive tests fail.  Not sure if it is the software issue or hardware at the moment.  Fixes will be posted in the "summit_cmake" branch.

**Comment by uhaehner** [comment]
The extensive tests that use MPI pass if `--smpiargs=none` is removed, which makes sense.
After the tests have passed, I still get the following error, though:
https://gist.github.com/uhaehner/35fbdeef44b2845f1f19e6dcce0dbda9

**Comment by uhaehner** [comment]
Adding `--smpiargs="-tcp"` to the `jsrun` command fixed it.
Reference: https://github.com/uber/horovod/issues/308

I'll try to get some more infos on this issue at the Summit workshop tomorrow.

**Comment by uhaehner** [comment]
SpAccumulatorGpuTest.SumTo still fails randomly:

64/129 Testing: sp_accumulator_gpu_test
64/129 Test: sp_accumulator_gpu_test
Command: "/opt/ibm/spectrum_mpi/jsm_pmix/bin/jsrun" "-a" "1" "-n" "1" "-g" "1" "-c" "8" "--smpiargs=none" "/gpfs/wolf/proj-shared/gen113/haehneru/build/test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu_test"
Directory: /gpfs/wolf/proj-shared/gen113/haehneru/build/test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp
"sp_accumulator_gpu_test" start time: Dec 05 15:28 EST
Output:

Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from SpAccumulatorGpuTest
[ RUN      ] SpAccumulatorGpuTest.Accumulate
[       OK ] SpAccumulatorGpuTest.Accumulate (156 ms)
[ RUN      ] SpAccumulatorGpuTest.SumTo
/gpfs/wolf/proj-shared/gen113/haehneru/DCA/test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu_test.cpp:82: Failure
Expected: (5e-7) > (diff.l_inf), actual: 5e-07 vs inf
[  FAILED  ] SpAccumulatorGpuTest.SumTo (18 ms)
[----------] 2 tests from SpAccumulatorGpuTest (174 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (174 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SpAccumulatorGpuTest.SumTo

 1 FAILED TEST
<end of output>
Test time =   0.29 sec

Test Failed.
"sp_accumulator_gpu_test" end time: Dec 05 15:28 EST
"sp_accumulator_gpu_test" time elapsed: 00:00:00

**Comment by uhaehner** [comment]
Fail, pass, fail on three consecutive executions:

**bash-4.2$ jsrun -n 1 -a 1 -g 1 -c 8 --smpiargs=none ./sp_accumulator_gpu_test**
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from SpAccumulatorGpuTest
[ RUN      ] SpAccumulatorGpuTest.Accumulate
[       OK ] SpAccumulatorGpuTest.Accumulate (167 ms)
[ RUN      ] SpAccumulatorGpuTest.SumTo
/gpfs/wolf/proj-shared/gen113/haehneru/DCA/test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu_test.cpp:82: Failure
Expected: (5e-7) > (diff.l_inf), actual: 5e-07 vs inf
[  FAILED  ] SpAccumulatorGpuTest.SumTo (17 ms)
[----------] 2 tests from SpAccumulatorGpuTest (184 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (184 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SpAccumulatorGpuTest.SumTo

 1 FAILED TEST
**bash-4.2$ jsrun -n 1 -a 1 -g 1 -c 8 --smpiargs=none ./sp_accumulator_gpu_test**
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from SpAccumulatorGpuTest
[ RUN      ] SpAccumulatorGpuTest.Accumulate
[       OK ] SpAccumulatorGpuTest.Accumulate (156 ms)
[ RUN      ] SpAccumulatorGpuTest.SumTo
[       OK ] SpAccumulatorGpuTest.SumTo (17 ms)
[----------] 2 tests from SpAccumulatorGpuTest (173 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (173 ms total)
[  PASSED  ] 2 tests.
**bash-4.2$ jsrun -n 1 -a 1 -g 1 -c 8 --smpiargs=none ./sp_accumulator_gpu_test**
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from SpAccumulatorGpuTest
[ RUN      ] SpAccumulatorGpuTest.Accumulate
[       OK ] SpAccumulatorGpuTest.Accumulate (204 ms)
[ RUN      ] SpAccumulatorGpuTest.SumTo
/gpfs/wolf/proj-shared/gen113/haehneru/DCA/test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu_test.cpp:82: Failure
Expected: (5e-7) > (diff.l_inf), actual: 5e-07 vs 5.01839
[  FAILED  ] SpAccumulatorGpuTest.SumTo (18 ms)
[----------] 2 tests from SpAccumulatorGpuTest (222 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (222 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SpAccumulatorGpuTest.SumTo

 1 FAILED TEST

**Comment by yingwaili** [comment]
Updates:
1. All fast and extensive tests (except sp_accumulator_gpu_test mentioned by @uhaehner above) pass on Ascent (Note that Ascent is a small training cluster emulating Summit, but with newer libraries and modules. Hopefully the failed tests on Summit will go away after receiving new module upgrades).

2. But on Summit many extensive tests still fail (see above). 

3. The --smpiargs=-mxm flag used in summit.cmake is only a temporary solution that uses Mellanox's protocol and bypasses PAMI for MPI communications.  If we are sure that our tests is correct, this means a SpectrumMPI misbehavior and will need to be filed as a bug to IBM.

**Comment by uhaehner** [comment]
@yingwaili Does the test always fail the same way?
If I remember correctly, on Ascent I got inf, nan or some wrong number in a random manner.

**Comment by yingwaili** [comment]
@uhaehner @gbalduzz To me, the test alternatively passes and fails.  

**When it passes:**
jsrun -n 1 -a 1 -g 1 -c 8 --smpiargs=none ./sp_accumulator_gpu_test
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from SpAccumulatorGpuTest
[ RUN      ] SpAccumulatorGpuTest.Accumulate
[       OK ] SpAccumulatorGpuTest.Accumulate (296 ms)
[ RUN      ] SpAccumulatorGpuTest.SumTo
[       OK ] SpAccumulatorGpuTest.SumTo (17 ms)
[----------] 2 tests from SpAccumulatorGpuTest (313 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (313 ms total)
[  PASSED  ] 2 tests.

**When it fails:**
jsrun -n 1 -a 1 -g 1 -c 8 --smpiargs=none ./sp_accumulator_gpu_test
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from SpAccumulatorGpuTest
[ RUN      ] SpAccumulatorGpuTest.Accumulate
[       OK ] SpAccumulatorGpuTest.Accumulate (263 ms)
[ RUN      ] SpAccumulatorGpuTest.SumTo
/gpfs/alpine/stf006/scratch/ywl/ctest/DCA/test/unit/phys/dca_step/cluster_solver/shared_tools/accumulation/sp/sp_accumulator_gpu_test.cpp:82: Failure
Expected: (5e-7) > (diff.l_inf), actual: 5e-07 vs 5.00579
[  FAILED  ] SpAccumulatorGpuTest.SumTo (17 ms)
[----------] 2 tests from SpAccumulatorGpuTest (280 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (280 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SpAccumulatorGpuTest.SumTo

 1 FAILED TEST
