### ISSUE TITLE
Broadcast fails for functions larger than 2^31-1 bytes.

### ISSUE THREAD

**Issue by gbalduzz** [CompFUSE/DCA#99]
The broadcast of a function relies on packing all the values. On top of being inefficient, this limits the size of the maximum packable function to the size of a positive 32 bits integer in bytes, which is easily reachable with a large G4 accumulation.

**Comment by yingwaili** [comment]
Do you see this on different machines?

**Comment by gbalduzz** [comment]
No only on summit. Closed via #116
